// ══════════════════════════════════════════════════════════════
// TEGRITY VOYAGE MANAGEMENT (TVM) — SHARED CORE & SEED DATASET
// Replicating & expanding dataset from TegrityVoyageIQ
// ══════════════════════════════════════════════════════════════

export const ORGANIZATIONS = [
  { id: 'org-tegrity',        name: 'TegrityTec Shipping Pte. Ltd.',     code: 'TEG', type: 'Carrier / Ship Owner',     status: 'Active', domain: 'tegritytec.com',      taxId: 'SG-2026-8819', country: 'Singapore', contactEmail: 'ops@tegritytec.com', maxUsers: 50, createdDate: '2026-01-10' },
  { id: 'org-oceanneptune',   name: 'OceanNeptune Chartering Ltd.',      code: 'ONC', type: 'Charterer / Trader',       status: 'Active', domain: 'oceanneptune.com',    taxId: 'UK-7729-1002', country: 'United Kingdom', contactEmail: 'chartering@oceanneptune.com', maxUsers: 25, createdDate: '2026-02-01' },
  { id: 'org-pacificrefining',name: 'Pacific Refining & Energy Corp',     code: 'PRE', type: 'Shipper / Cargo Interest', status: 'Active', domain: 'pacificrefining.com', taxId: 'US-9912-4410', country: 'USA', contactEmail: 'logistics@pacificrefining.com', maxUsers: 30, createdDate: '2026-02-15' },
  { id: 'org-globalmaritime', name: 'Global Maritime Services Inc.',     code: 'GMS', type: 'Port Agency & Ops',        status: 'Active', domain: 'globalmaritime.org',  taxId: 'AE-3310-5591', country: 'UAE', contactEmail: 'agency@globalmaritime.org', maxUsers: 20, createdDate: '2026-03-01' },
  { id: 'org-gardpi',         name: 'Gard P&I Club & Marine Insurance',  code: 'GARD',type: 'Insurer / P&I Club',       status: 'Active', domain: 'gard.no',             taxId: 'NO-5519-0012', country: 'Norway', contactEmail: 'claims@gard.no', maxUsers: 15, createdDate: '2026-04-01' },
];

export const FLEETS = [
  { id: 'flt-tanker-crude', name: 'Crude Tanker Fleet', type: 'Tanker', organizationId: 'org-tegrity', manager: 'Capt. Marcus Vance', vesselCount: 2, description: 'Aframax & Suezmax crude carriers operating global routes', status: 'Active' },
  { id: 'flt-tanker-mr',    name: 'MR Product Tanker Fleet', type: 'Tanker', organizationId: 'org-tegrity', manager: 'Elena Rostova', vesselCount: 2, description: 'Medium Range refined petroleum product carriers', status: 'Active' },
  { id: 'flt-drybulk',      name: 'Panamax Dry Bulk Fleet', type: 'Dry Bulk', organizationId: 'org-oceanneptune', manager: 'Simon De Vries', vesselCount: 1, description: 'Panamax grain & ore bulkers in Atlantic/Pacific trades', status: 'Active' },
  { id: 'flt-gas',          name: 'LPG / Gas Carrier Fleet', type: 'Gas Carrier', organizationId: 'org-tegrity', manager: 'Astrid Lindgren', vesselCount: 1, description: 'Pressurized & semi-refrigerated gas carriers', status: 'Active' },
];

export const VESSELS = [
  { imo:'9200101', name:'MT Tegrity Apex',    type:'Crude Tanker',     fleetId:'flt-tanker-crude', fleetType:'Tanker', flag:'Singapore',        dwt:110000, builtYear:2022, owner:'TegrityTec Shipping Pte. Ltd.', organizationId:'org-tegrity', status:'Active' },
  { imo:'9200102', name:'MV Tegrity Crest',   type:'MR Product Tanker',fleetId:'flt-tanker-mr',    fleetType:'Tanker', flag:'Marshall Islands', dwt:47000,  builtYear:2021, owner:'TegrityTec Shipping Pte. Ltd.', organizationId:'org-tegrity', status:'Active' },
  { imo:'9200103', name:'MV Tegrity Pacific', type:'Dry Bulk',         fleetId:'flt-drybulk',      fleetType:'Dry Bulk', flag:'Panama',           dwt:78000,  builtYear:2020, owner:'Ocean Neptune Chartering Ltd.', organizationId:'org-oceanneptune', status:'Active' },
  { imo:'9200104', name:'MT Tegrity Prime',   type:'Crude Tanker',     fleetId:'flt-tanker-crude', fleetType:'Tanker', flag:'Bahamas',          dwt:130000, builtYear:2023, owner:'TegrityTec Shipping Pte. Ltd.', organizationId:'org-tegrity', status:'Active' },
  { imo:'9200105', name:'MV Tegrity Meridian', type:'LPG Carrier',      fleetId:'flt-gas',          fleetType:'Gas Carrier', flag:'Norway',           dwt:55000,  builtYear:2024, owner:'TegrityTec Shipping Pte. Ltd.', organizationId:'org-tegrity', status:'Active' },
  { imo:'9200106', name:'MV Tegrity Vigil',   type:'Chemical Tanker',  fleetId:'flt-tanker-mr',    fleetType:'Tanker', flag:'Singapore',        dwt:38500,  builtYear:2022, owner:'Ocean Neptune Chartering Ltd.', organizationId:'org-oceanneptune', status:'Active' },
];

export const CHARTER_PARTIES = [
  { cpId: 'CP-BPVOY4-01', cpForm: 'BPVOY4', charterType: 'Voyage', charterer: 'Shell International Trading', owner: 'TegrityTec Shipping Pte. Ltd.', governingLaw: 'English Law', laytimeTerms: '72 Hours SHINC', demurrageRate: 42000, claimsTimeBar: '90 Days from Discharge', status: 'Active' },
  { cpId: 'CP-SHELLVOY6-01', cpForm: 'SHELLVOY6', charterType: 'Voyage', charterer: 'BP Oil International', owner: 'TegrityTec Shipping Pte. Ltd.', governingLaw: 'English Law', laytimeTerms: '84 Hours SHEX EIU', demurrageRate: 38500, claimsTimeBar: '60 Days from Discharge', status: 'Active' },
  { cpId: 'CP-NYPE93-01', cpForm: 'NYPE 93', charterType: 'Time', charterer: 'Pacific Refining & Energy Corp', owner: 'TegrityTec Shipping Pte. Ltd.', governingLaw: 'New York Law', laytimeTerms: 'N/A (Hire & Off-Hire)', demurrageRate: 0, claimsTimeBar: '120 Days from Expiry', status: 'Active' },
  { cpId: 'CP-ASBA-01', cpForm: 'ASBATANKVOY', charterType: 'Voyage', charterer: 'Chevron Products Trading', owner: 'Ocean Neptune Chartering Ltd.', governingLaw: 'New York Law', laytimeTerms: '72 Hours SHINC WIBON', demurrageRate: 45000, claimsTimeBar: '90 Days from Discharge', status: 'Active' },
  { cpId: 'CP-BARECON-01', cpForm: 'BARECON 2017', charterType: 'Bareboat', charterer: 'Ocean Neptune Chartering Ltd.', owner: 'TegrityTec Shipping Pte. Ltd.', governingLaw: 'English Law', laytimeTerms: 'N/A (Bareboat Demise)', demurrageRate: 0, claimsTimeBar: '180 Days from Expiry', status: 'Active' },
];

export const TIME_CONTRACTS = [
  { contractId: 'TC-2026-001', vesselImo: '9200101', vesselName: 'MT Tegrity Apex', organizationId: 'org-tegrity', chartererName: 'Ocean Neptune Chartering Ltd.', hireRatePerDay: 38500, deliveryPort: 'Ras Tanura, KSA', redeliveryPort: 'Singapore Pilot Station', commenceDate: '2026-01-15', expiryDate: '2026-12-31', fuelSpecs: 'VLSFO 0.5% Max / LSMGO 0.1%', performanceWarranty: '14.5 knots @ 42 MT/day VLSFO (Laden)', status: 'Active' },
  { contractId: 'TC-2026-002', vesselImo: '9200103', vesselName: 'MV Tegrity Pacific', organizationId: 'org-oceanneptune', chartererName: 'Pacific Refining & Energy Corp', hireRatePerDay: 26500, deliveryPort: 'Richards Bay, South Africa', redeliveryPort: 'Rotterdam, Netherlands', commenceDate: '2026-03-01', expiryDate: '2027-02-28', fuelSpecs: 'VLSFO 0.5% S / LSMGO 0.1% S', performanceWarranty: '13.0 knots @ 28 MT/day VLSFO (Laden)', status: 'Active' },
  { contractId: 'TC-2026-003', vesselImo: '9200105', vesselName: 'MV Tegrity Meridian', organizationId: 'org-tegrity', chartererName: 'Global Maritime Services Inc.', hireRatePerDay: 42000, deliveryPort: 'Houston, USA', redeliveryPort: 'Chiba, Japan', commenceDate: '2026-05-10', expiryDate: '2027-05-09', fuelSpecs: 'LSMGO 0.1% / Dual-Fuel LPG', performanceWarranty: '16.0 knots @ 35 MT/day LPG', status: 'Active' },
];

export const VOYAGE_CONTRACTS = [
  { contractId: 'VC-2026-001', voyageNumber: 'TVQ-2026-001', vesselImo: '9200101', vesselName: 'MT Tegrity Apex', organizationId: 'org-tegrity', chartererName: 'Shell International Trading', loadPort: 'Ras Tanura (KSA)', dischargePort: 'Singapore (SGP)', cargoType: 'Arabian Light Crude Oil', quantityMT: 105000, freightRateUSD: 24.50, laycanStart: '2026-03-28', laycanEnd: '2026-04-02', status: 'Active' },
  { contractId: 'VC-2026-002', voyageNumber: 'TVQ-2026-002', vesselImo: '9200102', vesselName: 'MV Tegrity Crest', organizationId: 'org-tegrity', chartererName: 'BP Oil International', loadPort: 'Fawley (UK)', dischargePort: 'Rotterdam (NLD)', cargoType: 'Ultra-Low Sulfur Diesel', quantityMT: 42000, freightRateUSD: 18.75, laycanStart: '2026-03-20', laycanEnd: '2026-03-25', status: 'Active' },
  { contractId: 'VC-2026-003', voyageNumber: 'TVQ-2026-003', vesselImo: '9200104', vesselName: 'MT Tegrity Prime', organizationId: 'org-tegrity', chartererName: 'Pacific Refining & Energy Corp', loadPort: 'Corpus Christi (USA)', dischargePort: 'Ningbo (CHN)', cargoType: 'West Texas Intermediate Crude', quantityMT: 125000, freightRateUSD: 31.20, laycanStart: '2026-04-10', laycanEnd: '2026-04-15', status: 'Pending' },
  { contractId: 'VC-2026-004', voyageNumber: 'TVQ-2026-004', vesselImo: '9200106', vesselName: 'MV Tegrity Vigil', organizationId: 'org-oceanneptune', chartererName: 'Global Maritime Services Inc.', loadPort: 'Antwerp (BEL)', dischargePort: 'Jebel Ali (UAE)', cargoType: 'Paraxylene / Chemical', quantityMT: 35000, freightRateUSD: 44.00, laycanStart: '2026-04-01', laycanEnd: '2026-04-06', status: 'Active' },
];

export const RIDER_CLAUSES = [
  { clauseId: 'RC-001', title: 'NOR Tender WIBON / WIPON Clause', category: 'NOR & Laytime', associatedContractId: 'VC-2026-001', riderText: 'Notice of Readiness (NOR) may be tendered whether in berth or not (WIBON), whether in port or not (WIPON), whether in free pratique or not (WIFON), whether customs cleared or not (WICONS).', overridesPrintedForm: true, status: 'Active' },
  { clauseId: 'RC-002', title: 'EU ETS Carbon Allowance Indemnity Clause', category: 'Environmental & EU ETS', associatedContractId: 'TC-2026-001', riderText: 'Charterers shall surrender to Owners EU Allowances (EUAs) corresponding to the vessel emission footprint during the Charter Period within 10 days of monthly emissions confirmation.', overridesPrintedForm: true, status: 'Active' },
  { clauseId: 'RC-003', title: 'BIMCO War Risk / Red Sea Transit Clause 2023', category: 'Sanctions & War Risk', associatedContractId: 'VC-2026-001', riderText: 'Vessel shall not be required to transit Red Sea or Bab el-Mandeb Strait if in Master or Owners judgment reasonably dangerous. Additional War Risk Premiums (AP) are 100% for Charterers account.', overridesPrintedForm: true, status: 'Active' },
  { clauseId: 'RC-004', title: 'Pumping Warranty & Pressure Exception', category: 'Cargo & Tank Cleaning', associatedContractId: 'VC-2026-002', riderText: 'Vessel warrants discharging total cargo volume within 24 hours or maintaining back pressure of 7.0 bar at ship shore manifold, provided shore facilities permit.', overridesPrintedForm: false, status: 'Active' },
  { clauseId: 'RC-005', title: 'BIMCO Hull Fouling Clause 2019', category: 'Bunkers & Performance', associatedContractId: 'TC-2026-002', riderText: 'If Vessel remains idle at Charterers request in tropical waters for >14 days, performance warranties are suspended until underwater hull inspection and cleaning are performed at Charterers expense.', overridesPrintedForm: true, status: 'Active' },
];

export const MASTER_INSTRUCTIONS = [
  { instructionId: 'TVI-2026-001-A', instructionNo: 'TVI-2026-001-A', contractId: 'VC-2026-001', vesselImo: '9200101', vesselName: 'MT Tegrity Apex', issuedBy: 'Voyage Operator — TegrityTec Chartering', issuedTo: 'Master, MT Tegrity Apex', issueDate: '2026-03-25', priority: 'High', loadingInstructions: 'Tender NOR immediately upon reaching Ras Tanura outer anchorage WIBON. Verify shore line displacement before loading crude.', bunkeringInstructions: 'Lift 600 MT VLSFO at Fujairah en route to Singapore if ROB drops below 400 MT. Confirm 3 quotes before ordering.', specialClauseNote: 'Ensure full deck log entries during weather holds to substantiate laytime exclusion exceptions under BPVOY4 Clause 16.', status: 'Issued' },
  { instructionId: 'TVI-2026-002-A', instructionNo: 'TVI-2026-002-A', contractId: 'VC-2026-002', vesselImo: '9200102', vesselName: 'MV Tegrity Crest', issuedBy: 'Voyage Operator — TegrityTec Chartering', issuedTo: 'Master, MV Tegrity Crest', issueDate: '2026-03-18', priority: 'Routine', loadingInstructions: 'Maintain nitrogen purging certificates for tanks 1P/S and 3P/S prior to loading ULSD at Fawley.', bunkeringInstructions: 'No bunkering required; sufficient ROB for round voyage to Rotterdam.', specialClauseNote: 'SHEX EIU laytime terms apply — secure terminal time-sheets confirming any Sunday hours worked.', status: 'Acknowledged' },
  { instructionId: 'TVI-2026-003-A', instructionNo: 'TVI-2026-003-A', contractId: 'TC-2026-001', vesselImo: '9200103', vesselName: 'MV Tegrity Pacific', issuedBy: 'Fleet Commercial Manager — OceanNeptune', issuedTo: 'Master, MV Tegrity Pacific', issueDate: '2026-03-22', priority: 'Urgent', loadingInstructions: 'Proceed at eco speed (12.0 knots) to Richards Bay. Advise 72/48/24 hrs ETA updates to Richards Bay Coal Terminal.', bunkeringInstructions: 'Bunker 450 MT VLSFO at Durban prior to loading berth allocation.', specialClauseNote: 'BIMCO Hull Fouling Clause active — log daily sea water temperature at anchorage.', status: 'Issued' },
];

export const INSURANCE_POLICIES = [
  { policyId: 'POL-PI-2026-01', policyNo: 'GARD-9200101-2026', vesselImo: '9200101', vesselName: 'MT Tegrity Apex', policyType: 'P&I Club', insurer: 'Gard P&I Club', insuredLimit: '$500,000,000', deductible: '$50,000', expiryDate: '2027-02-20', status: 'Active' },
  { policyId: 'POL-HM-2026-01', policyNo: 'LLD-HM-9200101', vesselImo: '9200101', vesselName: 'MT Tegrity Apex', policyType: 'Hull & Machinery', insurer: 'Lloyds Syndicate 2003', insuredLimit: '$85,000,000', deductible: '$100,000', expiryDate: '2026-12-31', status: 'Active' },
  { policyId: 'POL-PI-2026-02', policyNo: 'NS-9200102-2026', vesselImo: '9200102', vesselName: 'MV Tegrity Crest', policyType: 'P&I Club', insurer: 'NorthStandard P&I', insuredLimit: '$500,000,000', deductible: '$35,000', expiryDate: '2027-02-20', status: 'Active' },
  { policyId: 'POL-WR-2026-01', policyNo: 'HWR-2026-9201', vesselImo: '9200104', vesselName: 'MT Tegrity Prime', policyType: 'War Risk', insurer: 'Hellenic War Risks', insuredLimit: '$130,000,000', deductible: '$25,000', expiryDate: '2026-12-31', status: 'Active' },
  { policyId: 'POL-LOH-2026-01', policyNo: 'NHC-LOH-9203', vesselImo: '9200103', vesselName: 'MV Tegrity Pacific', policyType: 'Loss of Hire', insurer: 'Norwegian Hull Club', insuredLimit: '$28,500 / Day (Max 90 Days)', deductible: '14 Days Franchise', expiryDate: '2027-04-15', status: 'Active' },
  { policyId: 'POL-CG-2026-01', policyNo: 'BRIT-CG-9204', vesselImo: '9200105', vesselName: 'MV Tegrity Meridian', policyType: 'Cargo Liability', insurer: 'Britannia P&I Club', insuredLimit: '$50,000,000', deductible: '$20,000', expiryDate: '2027-02-20', status: 'Active' },
];
